#!/bin/bash

PROJ_DIR="$(dirname "$0")"

if [ "$#" -gt 0 ] && [ "$1" = "--kill" ]; then
  shift
  if [ -f "$PROJ_DIR/.pid" ]; then
    sudo fuser -k -n tcp 80
    rm "$PROJ_DIR/.pid" 2>/dev/null
  else
    echo "Nothing to kill!"
  fi
  if [ "$#" -eq 0 ]; then
    exit 0
  fi
fi

if [ -f "$PROJ_DIR/.env" ]; then
  . "$PROJ_DIR/.env"
fi

if [ "$#" -eq 2 ] && [ "$1" = "db" ] && [ "$2" = "serve" ]; then
  if [ -f "$PROJ_DIR/.pid" ]; then
    sudo fuser -k -n tcp 80
  fi

  echo "Running in disowned process as root..."
  sudo echo -n ""
  sudo -E java -jar "$PROJ_DIR/.build/libs/schedge-all.jar" $@ & disown
  echo "$!" > "$PROJ_DIR/.pid"
else
  java -jar "$PROJ_DIR/.build/libs/schedge-all.jar" $@
fi




