#!/bin/bash

PROJ_DIR="$(dirname "$(dirname "$0")")"

if [ -f "$PROJ_DIR/.pid" ]; then
  sudo bash -c "kill '$(cat "$PROJ_DIR/.pid")' 1>/dev/null 2>&1"
fi

if [ "$#" -gt 0 ] && [ "$1" = "--production" ]; then
  shift
  echo "Running in disowned process as root"
  sudo java -jar .build/libs/schedge-all.jar $@ & disown
  echo "$!" > "$PROJ_DIR/.pid"
else
  java -jar .build/libs/schedge-all.jar $@
  rm "$PROJ_DIR/.pid" 2>/dev/null
fi




