#!/bin/bash

PROJ_DIR="$(dirname "$0")"

cd "$PROJ_DIR"

if [ "$#" -gt 0 ] && [ "$1" = "--kill" ]; then
  shift
  if [ -f "$PROJ_DIR/.pid" ]; then
    (cat "$PROJ_DIR/.pid" | xargs kill)
    rm "$PROJ_DIR/.pid" 2>/dev/null
  else
    echo "Nothing to kill!"
  fi
  if [ "$#" -eq 0 ]; then
    exit 0
  fi
fi

if [ -f "$PROJ_DIR/.env" ]; then
  . "$PROJ_DIR/.env"
fi

echo "Running in disowned process..."
if [ -f "$PROJ_DIR/.pid" ]; then
  (cat "$PROJ_DIR/.pid" | xargs kill)
  rm .pid
fi

java -Xmx1G -Djdk.httpclient.allowRestrictedHeaders=host,connection \
  -jar "$PROJ_DIR/.build/libs/schedge.jar" $@ & disown
echo "$!" > "$PROJ_DIR/.pid"
