#!/bin/sh

function setup_postgres() {
docker run \
  --name pg-docker \
  -e POSTGRES_PASSWORD=docker \
  -d -p 5432:5432 \
  -v postgres:/var/lib/postgresql/data postgres
createuser schedge
}

docker start pg-docker 2>1 > /dev/null || setup_postgres

