name: Deploy

on:
  push:
    branches: [ production ]

jobs:
  Backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: src/build/docker/Dockerfile
          push: true
          tags: ghcr.io/A1Liu/schedge:latest

  Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      # - run: yarn install --frozen-lockfile

      # - name: Build
      #   run: |
      #     yarn build
      #     touch .dist/.nojekyll
      #     echo galbert.a1liu.com >> .dist/CNAME

      # - name: Deploy
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git --work-tree .dist add --all
      #     git commit -m "Automatic Deploy action run by github-actions"
      #     git push origin HEAD:gh-pages --force
