name: Deploy

on:
  push:
    branches: [ production ]

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  Frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      # - run: yarn install --frozen-lockfile

      # - name: Build
      #   run: |
      #     yarn build
      #     touch .dist/.nojekyll
      #     echo galbert.a1liu.com >> .dist/CNAME

      # - name: Deploy
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git --work-tree .dist add --all
      #     git commit -m "Automatic Deploy action run by github-actions"
      #     git push origin HEAD:gh-pages --force
