name: Deploy

on:
  workflow_dispatch:

jobs:
  Server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Node + Yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      
      # https://nextjs.org/docs/advanced-features/ci-build-caching
      - name: Cache NextJS Files
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'

      - run: yarn install --frozen-lockfile
      - run: yarn export

      - name: Build with Gradle
        run: yarn gradle jar

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/build/docker/Dockerfile
          push: true
          tags: ghcr.io/a1liu/schedge:latest
