name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Node + Yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install JS Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint React Formatting
        run: yarn format

      - name: Check for Changes
        run: git diff --exit-code

  java:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Run Java Formatter
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
        source: './src/main/java ./src/test/java'
        extensions: 'java'
        clangFormatVersion: 15
        inplace: True

      - name: Check for Changes
        run: git diff --exit-code
