name: Java - Check Formatting

on:
  push:

jobs:
  java-linter:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Run Java Formatter
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: './src/main/java ./src/test/java'
          extensions: 'java'
          clangFormatVersion: 14
          inplace: True

      - name: Display Changes
        run: git diff

      - name: Check for Changes
        run: git diff --exit-code --name-only
