name: Java - Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  java-test:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14.1-alpine

        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

        # Maps tcp port 5432 on service container to the host
        ports:
          - 5432:5432

    # container: ubuntu:22.04
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JDBC_URL: jdbc:postgresql://localhost:5432/postgres

    steps:
      # Disabling for now and seeing what happens
    - name: Validate Job Run For Scraping
      run: exit 1
      if: >
        false
        && github.ref != 'refs/heads/main'
        && !contains(github.event.head_commit.message, 'RUN_TEST')

    - name: Checkout Project
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Node + Yarn
      uses: actions/setup-node@v3
      with:
        cache: 'yarn'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build JAR file
      run: |
        yarn gradle jar

    # Command lifted from `src/build/docker/entrypoint.sh`
    - name: Scrape terms
      run: >
        java -Xmx1G -Djdk.httpclient.allowRestrictedHeaders=host,connection
        -jar .build/libs/schedge.jar
        db ci-populate
        sp2021/CSCI-UA sp2021/SCA-UA_1 sp2021/MATH-UA sp2021/DS-UA
        fa2022/CSCI-UA
        sp2023/ITPG-GT sp2023/MASY1-GC sp2023/CSCI-UA sp2023/DM-UY sp2023/CS-UY
        sp2023/INTG1-GC sp2023/PUBB1-GC sp2023/URPL-GP sp2023/DHSS-GA sp2023/OART-UT
        sp2023/OART-GT sp2023/COART-UT sp2023/IMNY-UT sp2023/PWRT1-GC

    - name: Test Code
      id: test-code
      run: yarn test
