name: Deploy

on:
  workflow_dispatch:

jobs:
  Scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          with:
            lfs: true
