name: Scrape Term

on:
  workflow_dispatch:
    inputs:
      term:
        required: true
        description: Term to scrape (e.g. sp2021)

jobs:
  Scrape:
    runs-on: ubuntu-latest
    environment: admin
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node + Yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install JS Dependencies
        run: yarn install --frozen-lockfile

      - name: Run
        run: yarn wscat -c "wss://nyu.a1liu.com/api/scrape/${{ github.event.inputs.term }}" --auth "${{ secrets.SCHEDGE_PASSWORD }}"
