name: Scrape Term

on:
  workflow_dispatch:
    inputs:
      term:
        required: true
        description: Term to scrape (e.g. sp2021)
      source:
        required: false
        description: Source to scrape from (either schedge-v1 or sis.nyu.edu)

jobs:
  Scrape:
    runs-on: ubuntu-latest
    environment: admin
    permissions:
      contents: read

    steps:
      - name: Install Websocat
        run: wget https://github.com/vi/websocat/releases/download/v1.11.0/websocat.x86_64-unknown-linux-musl -O ./websocat

      - name: Update Permissions
        run: chmod +x ./websocat

      - name: Run Scrape on ${{ github.event.inputs.term }}
        run: >
          ./websocat
          "wss://nyu.a1liu.com/api/scrape/${{ github.event.inputs.term }}?source=${{ github.event.inputs.source }}"
          -n --basic-auth "${{ secrets.SCHEDGE_PASSWORD }}"
